app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', 'ChannelController@index');
Route::get('/index', 'ChannelController@index');
Route::auth();

Route::get('/admin', 'HomeController@index')->name('adminindex');

Route::get('/Contact', 'ChannelController@Contact');
Route::get('/Livestream', 'ChannelController@Livestream');
Route::get('/History', 'ChannelController@History');
Route::get('/feeds' , 'ChannelController@NewsFeed');
Route::get('/nacc' , 'ChannelController@Nacc');
Route::get('/pacc' , 'ChannelController@Pacc');
Route::get('/test' , 'ChannelController@Test');

Route::resource('/admin/infographics','InfoGraphicController');
Route::resource('/admin/youtube','YoutubeController');
//Route::resource('/library','LibraryController');
Route::resource('/admin/newstopic','NewsController');
Route::resource('/admin/category','CategoryController');
Route::resource('/admin/categorynews','CategoryNewsController');
Route::resource('/admin/categoryinfographics','CategoryInfographicController');
//Route::resource('/playyoutube','PlayYoutubeController');
// manage user 
Route::resource('/admin/users','UsersController');

Route::delete('/ajaxdeletenewsdetail/{id}', 'NewsController@ajaxdeletenewsdetail')->name('ajaxdeletenewsdetail');
Route::post('/ajaxupdateview', 'ChannelController@ajaxupdateview')->name('ajaxupdateview'); 
Route::post('/ajaxupdateviewinfographic', 'ChannelController@ajaxupdateinfographic')->name('ajaxupdateinfographic'); 
Route::post('/ajaxupdateviewnews', 'ChannelController@ajaxupdateviewnews')->name('ajaxupdateviewnews');//Ajax Route to function ajaxupdateview
Route::get('PlayYoutube/{id}', [
    'as' => 'PlayYoutube',
    'uses' => 'ChannelController@PlayYoutube'
]);
Route::resource('playyoutube', 'ChannelController', ['except' => 'PlayYoutube']);

Route::get('Category/{id}', [
    'as' => 'Category',
    'uses' => 'ChannelController@Category'
]);
Route::resource('Category', 'ChannelController', ['except' => 'Category']);

Route::get('Infographic/{id}', [
    'as' => 'Infographic',
    'uses' => 'ChannelController@Infographic'
]);
Route::resource('viewinfographicc', 'ChannelController', ['except' => 'Infographic']);

Route::get('News/{id}', [
    'as' => 'News',
    'uses' => 'ChannelController@News'
]);
Route::resource('viewnews', 'ChannelController', ['except' => 'News']);

Route::get('Detailnews/{id}', [
    'as' => 'Detailnews',
    'uses' => 'ChannelController@Detailnews'
]);
Route::resource('viewdetailnew', 'ChannelController', ['except' => 'Detailnews']);

resources/views/contactus.blade.php
@extends('layouts.frontend')
@section('content')
<section id="breadcrumb" class="breadcrumb-video-2">
        <div class="row">
            <div class="large-12 columns">
                <nav aria-label="You are here:" role="navigation">
                    <ul class="breadcrumbs">
                    <li><i class="fa fa-home"></i><a href="{{url('/')}}">หน้าหลัก</a></li>
                        <li><a href="">ติอต่อเรา</a></li>
                        
                    </ul>
                </nav>
            </div>
        </div>
    </section>
    <section class="category-content">
        <div class="row">
            <!-- left side content area -->
            <div class="large-8 columns">
                <section class="content content-with-sidebar">
                    <!-- newest video -->
                    <div class="main-heading removeMargin">
                        <div class="row secBg padding-14 removeBorderBottom">
                            <div class="medium-8 small-8 columns">
                                <div class="head-title">
                                    <i class="fa fa-user"></i>
                                    <h4>ติดต่อเรา </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row secBg">
                        <div class="large-12 columns">
                            <article class="page-content">
                                <center>
                                    <a href="{{asset('frontend/images/map.jpg')}}" data-lightbox="lightboxOverlay" data-title="">
                                        <img src="{{asset('frontend/images/map.jpg')}}" alt="">
                                        <span><i class=""></i></span>
                                    </a>
                                </center>
                                   <br>
                                   <h6>สถานที่ตั้ง : กรมประชาสัมพันธ์ เลขที่9 ซอยอารีย์สัมพันธ์ ถนนพระราม 6 แขวงสามเสนใน เขตพญาไท กรุงเทพฯ 10400 </h6>
                                   <h6>โทร : 02-618-2323 โทรสาร : 02-618-2364, 618-2399</h6> 
                                   <h6> Website : http://www.prd.go.th </h6>
                                   <h6> E-mail : webmaster@prd.go.th </h6>
                                   
                                 @include('layouts.sharesocial')
                            </article>
                        </div>
                    </div>
                </section>  
                   
            </div><!-- end left side content area -->
            <!-- sidebar -->
            <div class="large-4 columns">
                <aside class="secBg sidebar"> 
                    <div class="row">
                        <!-- social Fans Widget -->
                      @include('layouts.social')
                      <!-- End social Fans Widget -->
                    </div>
                </aside>
            </div><!-- end sidebar -->
        </div>
    </section><!-- End Category Content-->
@endsection

resources/views/feeds.blade.php
@extends('layouts.frontend') 
    @section('content')
<!--breadcrumbs-->
            <section id="breadcrumb">
                <div class="row">
                    <div class="large-12 columns">
                        <nav aria-label="You are here:" role="navigation">
                            <ul class="breadcrumbs">
                                <li>
                                    <i class="fa fa-home"></i>
                                    <a href="{{url('/')}}">หน้าหลัก</a>
                                </li>
                                <li>
                                    <span class="show-for-sr">Current: </span> สำนักข่าว NNT
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </section>
            <!--end breadcrumbs-->
            <br>

            <section class="category-content">
                <div class="row">
                    <!-- left side content area -->
                    <div class="large-8 columns">
                        <section class="content content-with-sidebar">
                            <!-- newest video -->
                            <div class="main-heading removeMargin">
                                <div class="row secBg padding-14 removeBorderBottom">
                                    <div class="medium-8 small-8 columns">
                                        <div class="head-title">
                                            <i class="fa fa-newspaper-o"></i>
                                            สำนักข่าว NNT
                                        </div>
                                    </div>
                                    <div class="medium-4 small-4 columns">
                                        <ul class="tabs text-right pull-right" data-tabs id="newVideos">
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="row secBg">
                                <div class="large-12 columns">
                                    <div class="row column head-text clearfix">
                                        <p class="pull-left">All News :
                                            <span> 1 News posted</span>
                                        </p>
                                        </p>
                                        <div class="grid-system pull-right show-for-large">
                                            <a class="secondary-button current grid-medium" href="#">
                                                <i class="fa fa-th-large"></i>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="tabs-content" data-tabs-content="newVideos">
                                        <div class="tabs-panel is-active" id="new-all">
                                            <div class="row list-group">
                                                @foreach ($data->items as $item)
                                                <div class="item large-4 end columns grid-medium">
                                                    <div class="post thumb-border">
                                                        <div class="post-thumb">
                                                            <img alt="Image" src="{{ $item->get_enclosure()->link }}">
                                                            <a href="{{ $item->get_permalink() }}" class="hover-posts">
                                                                <span><i class="fa fa-play"></i>ดูรายละเอียด</span>
                                                            </a>
                                                        </div>
                                                        <div class="post-des">
                                                            {{--
                                                            <h6>{{ str_limit($item->title, 50,'...') }}</h6> --}}
                                                            <h5>{{ str_limit($item->get_title(), 70, '...' ) }}</a></h5>
                                                            <div class="post-stats clearfix">
                                                                <p class="pull-left">
                                                                    <small>Posted on {{ $item->get_date('j F Y | g:i a') }}</small>
                                                                </p>
                                                            </div>
                                                            <div class="post-summary">
                                                                {{--
                                                                <p>{{$item->detail}}</p> --}}
                                                            </div>
                                                            <div class="post-button">
                                                                <a href="single-video-v2.html" class="secondary-button">
                                                                    <i class="fa fa-play-circle"></i>watch video</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </section>
                        </div>
                        <!-- end left side content area -->
                        <!-- sidebar -->
                        <div class="large-4 columns">
                            <aside class="secBg sidebar">
                                <div class="row">
                                    @include('layouts.social')
                                </div>
                            </aside>
                        </div>
                        <!-- end sidebar -->
                    </div>
                </div>
            </section>
<!-- End Category Content-->
<!-- footer -->


</div>
</div>
</div>
@endsection

resources/views/history.blade.php
@extends('layouts.frontend') 
@section('content')
<section id="breadcrumb" class="breadcrumb-video-2">
        <div class="row">
            <div class="large-12 columns">
                <nav aria-label="You are here:" role="navigation">
                    <ul class="breadcrumbs">
                    <li><i class="fa fa-home"></i><a href="{{url('/')}}">หน้าหลัก</a></li>
                        <li><a href="">เกี่ยวกับเรา</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>
<section class="category-content">
    <div class="row">
        <!-- left side content area -->
        <div class="large-8 columns">
            <section class="content content-with-sidebar">
                <!-- newest video -->
                <div class="main-heading removeMargin">
                    <div class="row secBg padding-14 removeBorderBottom">
                        <div class="medium-8 small-8 columns">
                            <div class="head-title">
                                <i class="fa fa-history"></i>
                                <h4>ประวัติและความเป็นมา</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row secBg">
                    <div class="large-12 columns">
                        <article class="page-content">
                            <h3>ตรากรมประชาสัมพันธ์</h3>
                            <center><img src="{{asset('frontend/images/logoprd.png')}}" alt=""></center>
                            <p style="text-indent: 2.5em;"> ตามประกาศสำนักนายกรัฐมนตรี ซึ่งปรากฎในราชกิจจานุเบกษา ตอนที่ 7 เล่มที่ 64 ลงวันที่ 4 กุมภาพันธ์ 2490 กำหนด เครื่องหมาย ราชการ "กรมโฆษณาการ” ให้เป็นรูป พระอินทร์ เป่าสังข์ เหาะลอย อยู่เหนือเมฆ มีวงกลม ล้อมรอบ ตามวรรณคดีกล่าวไว้ว่า พระอินทร์เป่าสังข์ ปลุก พระนารายณ์ ให้ตื่น จากบรรทมสินธุ์ ในสะดือทะเล เพื่อขึ้นมา ปราบเหตุร้าย ต่าง ๆ ในโลก อย่างไร ก็ดี โดยที่สังข์ ตามลัทธิ พราหมณ์ ถือว่า เป็นมงคล 3 คือ สังข์ ถือกำเนิด จาก พระพรหม ท้องสังข์ เคยเป็น ที่ซ่อน คัมภีร์พระเวท และตัวสังข์ มีรอยนิ้ว พระหัตถ์ ของ พระนารายณ์ ในพิธีทาง ศาสนา พราหมณ์ จึงมี การเป่าสังข์ เพื่อความ เป็นสิริมงคล ด้วย นอกจากนี้ พระในลัทธิชินโต ก็ใช้ สังข์เป่า ในพิธีมงคล พวกชาวเกาะ ทะเลใต้ เป่าสังข์ บอกสัญญาณระหว่างกัน ปรากฏว่าได้ยินไปไกลไม่แพ้เป่าเขา ควาย เนื่องจากงานประชาสัมพันธ์เป็นการโฆษณาเผยแพร่ และ อธิบาย ชี้แจง ให้ประชาชน เข้าใจ อย่างกว้างขวาง เป็นการสร้าง ความเข้าใจ อันดี โดยมีวิทยุ โทรทัศน์ หนังสือพิมพ์ และภาพยนตร์ เป็นเครื่องช่วย จึงเปรียบได้กับ การเป่าสังข์ ของเทวดา ในสมัยโบราณ เพื่อบอก สัญญาณ และเรียกประชุม นั่นเอง
                            
                            </p>
                            <h3>ประวัติกรมประชาสัมพันธ์</h3>
                            <p style="text-indent: 2.5em;">กรมประชาสัมพันธ์เป็นหน่วยงานประชาสัมพันธ์ ของรัฐบาล สังกัดสำนักนายกรัฐมนตรี
                                ทำหน้าที่เป็นสื่อกลาง ในการ เสริมสร้าง ความเข้าใจอันดี ระหว่าง รัฐบาล และหน่วยงาน ของรัฐบาล
                                กับประชาชน ตลอดจน ระหว่าง ประชาชน ด้วยกัน โดยวิธีการ ให้ข่าวสาร ความรู้ ข้อเท็จจริง และรับฟัง
                                ความคิดเห็น ของประชาชน เพื่อเสนอรัฐบาล และหน่วยงาน ที่เกี่ยวข้อง นอกจากนี้ ยังทำหน้าที่ โน้มน้าว
                                ชักจูง ประชาชน เพื่อก่อให้เกิด ความร่วมมือ แก่รัฐบาล และ หน่วยราชการ ต่าง ๆ ตาม แนวทาง ที่ถูกที่ควร
                                ในระบอบ ประชาธิปไตย โดยมี พระมหากษัตริย์ เป็นประมุข นอกจาก สำนักงานใหญ่ ในกรุงเทพ มหานคร
                                แล้ว กรมประชาสัมพันธ์ ยังมี สำนัก ประชาสัมพันธ์ เขต อีก 8 สำนัก ได้แก่ สปข.1 ขอนแก่น สปข.2
                                อุบลราชธานี สปข.3 ลำปาง สปข.4 พิษณุโลก สปข.5 สุราษฎร์ธานี สปข.6 สงขลา สปข.7 จันทบุรี และ
                                สปข.8 กาญจนบุรี เพื่อเผยแพร่ และ ประชาสัมพันธ์ ข่าวสาร ให้เข้าถึง ประชาชน ในส่วน ภูมิภาค
                                ขณะ เดียวกัน กรมประชาสัมพันธ์ ยังมี สำนักงาน ประชาสัมพันธ์ ครบทุก จังหวัด </p>
                            <p style="text-indent: 2.5em;">กรมประชาสัมพันธ์เริ่มก่อตั้งเมื่อ 3 พฤษภาคม 2476 ภายหลัง การเปลี่ยนแปลงการปกครอง
                                จากระบอบ สมบูรณาญาสิทธิราช มาเป็นระบอบ ประชาธิปไตย มีรัฐธรรมนูญ เป็นกฎหมาย สูงสุด ของประเทศ
                                โดยมีชื่อ ในระยะเริ่มแรก ว่า "กองโฆษณาการ” และได้เปลี่ยนชื่อเป็น สำนักงานโฆษณาการ” เมื่อวันที่
                                9 ธันวาคม 2476 และได้มีการพัฒนา ผลงาน มาเป็นลำดับ โดยมี การปรับปรุง และขยาย ความรับผิดชอบ
                                เพิ่มขึ้นทุก ๆ ระยะ ตามความ เจริญ ก้าวหน้า ทางวิชาการ สภาพของสังคม การเมือง เศรษฐกิจ และวัฒนธรรม
                                ตลอดจน นโยบายของรัฐบาล ในแต่ละสมัย และเปลี่ยนชื่อมาเป็น "กรมโฆษณาการ” เมื่อวันที่ 5 กรกฎาคม
                                2483 หลังจากนั้น 12 ปี ได้เปลี่ยนชื่อเป็น "กรมประชาสัมพันธ์” เมื่อวันที่ 8 มีนาคม 2495 3
                                พฤษภาคม 2476 ตั้งเป็น "กองการโฆษณา” โดยพระราชบัญญัติ จัดตั้งกระทรวงและกรม มีฐานะเป็น กรมอิสระ
                                ขึ้นตรงต่อคณะรัฐมนตรี 9 ธันวาคม 2476 เปลี่ยนชื่อเป็น "สำนักงานโฆษณาการ” มีฐานะเป็นกรม หัวหน้าสำนักงาน
                                เทียบเท่าอธิบดี แบ่งส่วนราชการเป็น 3 กอง คือ สำนักงาน เลขานุการกรม กองเผยแพร่ความรู้ และกองหนังสือพิมพ์
                                โดย ทำหน้าที่ หลัก 3 ประการ คือให้ข่าว และความรู้ แก่ประชาชน เพื่อป้องกัน ความเข้าใจผิด เกี่ยวกับรัฐบาล
                                และประเทศ โดยส่วนรวม 31 มีนาคม 2481 โอนกิจการด้านช่าง และทะเบียนวิทยุ จาก กรมไปรษณีย์ โทรเลข
                                มาขึ้นกับ สำนักงาน โฆษณาการ และมีการตั้ง โฆษณาการเขต ขึ้นเป็นเขตแรก ที่จังหวัด หนองคาย และ
                                ที่จังหวัด พระตะบอง เป็นเขตที่สอง 5 กรกฎาคม 2483 เปลี่ยนชื่อเป็น "กรมโฆษณาการ”และมีการตั้ง
                                กองการ ต่างประเทศ เพิ่มขึ้น เพื่อติดต่อ และ โฆษณาการ เผยแพร่ ข่าวสาร ต่อชาว ต่างประเทศ 4
                                สิงหาคม 2490 โอนสำนักงาน ส่งเสริมการท่องเที่ยว จากกระทรวงคมนาคม มาขึ้นกับ กรมโฆษณาการ 8 มีนาคม
                                2495 เปลี่ยนชื่อเป็น "กรมประชาสัมพันธ์” เพื่อให้เหมาะสมกับ ภาระหน้าที่ ในฐานะ แหล่ง การเผยแพร่
                                นโยบาย และ ผลงาน ของรัฐบาล รวมทั้ง เผยแพร่ ข่าวสาร การเมือง ศีลธรรม วัฒนธรรม ความรู้ และ
                                ความบันเทิง ตลอดจน เป็นสื่อกลาง สร้างความสัมพันธ์ อันดี ระหว่าง รัฐบาล กับ ประชาชนด้วย พ.ศ.
                                2497 ตั้ง "สำนักงานแถลงข่าวไทยในต่างประเทศ” ขึ้นที่ลอนดอน และวอชิงตัน และได้จัดตั้ง กองประชา
                                สัมพันธ์ ภาคพื้นที่ จังหวัด สุราษฎร์ธานี เป็นแห่งแรก ทำหน้าที่ เป็นหน่วยงาน สาขา ของ กรมประชาสัมพันธ์
                                ในภาคใต้ โดยเฉพาะ 1มกราคม2503โอนสำนักงานส่งเสริมการท่องเที่ยวไปรวมกับ องค์การส่งเสริมการท่องเที่ยวแห่งประเทศไทย
                                ซึ่งจัดตั้งขึ้นใหม่ และเพิ่มหน่วยงาน ระดับกอง คือ กองสำรวจประชามติ เพื่อสำรวจ และรับฟัง ความคิดเห็น
                                ของประชาชน พ.ศ.2503 ได้มีการติดตั้ง "กองประชาสัมพันธ์เขต" ขึ้นที่จังหวัดขอนแก่น ลำปาง และสงขลา
                                เพื่อเป็นหน่วยงานสาขาของกรมประชาสัมพันธ์ในภาคตะวันออกเฉียงเหนือ ภาคเหนือ และภาคใต้ตอนล่าง
                                20 ตุลาคม 2504 ตั้ง "โรงเรียนการประชาสัมพันธ์" ขึ้นในสังกัดกรมประชาสัมพันธ์ เพื่อเผยแพร่วิชาความรู้และส่งเสริมความเข้าใจเกี่ยวกับวิชาการประชาสัมพันธ์
                                และการติดต่อสื่อสาร พ.ศ.2513 ตั้ง "สำนักงานแถลงข่าวไทยขึ้นที่พนมเปญประเทศเขมร" ปัจจุบันยกเลิกไปแล้ว
                                21สิงหาคม2518มีพระราชกฤษฎีกา แบ่งส่วนราชการบริหารส่วนกลาง และราชการส่วนภูมิภาค ของกรมประชาสัมพันธ์ใหม่
                                โดยมีหน่วย ระดับกอง 15 หน่วยงาน มิถุนายน 2521 ตั้ง "สำนักงานแถลงข่าวไทยที่กัวลาลัมเปอร์ ประเทศมาเลเซีย"
                                1 มกราคม 2522 ตั้ง "สำนักงานแถลงข่าวไทยที่เจดดาห์ ประเทศซาอุดิอาระเบีย 17 กันยายน 2526 ตั้ง
                                "ศูนย์ประชาสัมพันธ์เขต 4 สุราษฎร์ธานี" เพิ่มขึ้น 1 แห่ง 7สิงหาคม2529มีพระราชกฤษฎีกาแบ่งส่วนราชการกรมประชาสัมพันธ์
                                ออกเป็นราชการบริหารส่วนกลาง(20หน่วยงาน)และราชการบริหารส่วนภูมิภาค (สำนักงานประชาสัมพันธ์จังหวัด)โดยเพิ่มหน่วยงานใหม่คือ
                                กองงานคณะกรรมการประชาสัมพันธ์แห่งชาติ,ศูนย์ประชาสัมพันธ์เขต5-8, และวิทยุโทรทัศน์แห่งชาติ
                                และสถานีวิทยุโทรทัศน์แห่งประเทศไทย ช่อง 11 วันที่26มีนาคม2540มีพระราชกฤษฎีกาแบ่งส่วนราชการกรมประชาสัมพันธ์
                                โดยแบ่งเป็นราชการบริหารส่วนกลาง22หน่วยงานและราชการบริหารส่วนภูมิภาค (สำนักงานประชาสัมพันธ์จังหวัด
                                75 จังหวัด)
                                <div>  <p>    <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
       
                                        <a  class="a2a_button_facebook"></a>
                                        <a class="a2a_button_twitter"></a>
                                        {{-- <a class="a2a_button_google_plus"></a> --}}
                                        <a class="a2a_button_line"></a>
                                        </div>
                                        <script async src="https://static.addtoany.com/menu/page.js"></script></p> </div>
                                        
                            </p>
                        </article>
                    </div>
                </div>
            </section>
        </div><!-- end left side content area -->
        <!-- sidebar -->
        <div class="large-4 columns">
            <aside class="secBg sidebar">
                <div class="row">
                    <!-- social Fans Widget -->
                    <div class="large-12 medium-7 medium-centered columns">
                        <div class="widgetBox">
                            <div class="widgetTitle">
                                <h5>แผนที่ตั้งกรมประชาสัมพันธ์</h5>
                            </div>
                            <div class="widgetContent">
                                <a href="{{asset('frontend/images/map.jpg')}}" data-lightbox="lightboxOverlay" data-title="">
                                    <img src="{{asset('frontend/images/map.jpg')}}" alt="">
                                    <span><i class=""></i></span>
                                </a>
                            </div>
                        </div>
                    </div>
                    @include('layouts.social')
                    <!-- End social Fans Widget -->
                </div>
            </aside>
        </div><!-- end sidebar -->
    </div>
</section><!-- End Category Content-->
<Br> 
@endsection

resources/views/home.blade.php
@extends('layouts.master') 
@section('content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>หน้าหลัก</h4>
                        <span> ระบบจัดการข้อมูลเว็ปไซต์ CPI CHANNEL </span>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="{{url('/admin')}}">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="page-body">
                    <div class="row">
                        <!-- Documents card start <-->
                        <div class="col-md-6 col-xl-6">
                            <div class="card client-blocks">
                                <div class="card-block">
                                    <a href="{{route('admin.categorynews.index')}}">
                                        <h5>ระบบจัดการหมวดหมู่ประชาสัมพันธ์</h5>
                                        <ul>
                                            <li>
                                                <i class="icofont icofont-news"></i>
                                            </li>
                                            <li class="text-right success-border">
                                                {{$categorynews_count}}
                                            </li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-6">
                            <div class="card client-blocks">
                                <div class="card-block">
                                    <a href="{{route('admin.newstopic.index')}}">
                                        <h5>ระบบจัดการข่าวประชาสัมพันธ์</h5>
                                        <ul>
                                            <li>
                                                <i class="icofont icofont-news"></i>
                                            </li>
                                            <li class="text-right success-border">
                                                {{$news_count}}
                                            </li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-6">
                            <div class="card client-blocks success-border">
                                <div class="card-block">
                                    <a href="{{route('admin.categoryinfographics.index')}}">
                                        <h5>ระบบจัดการหมวดหมู่กิจกรรม</h5>
                                        <ul>
                                            <li>
                                                <i class="icofont icofont-social-photobucket text-success"></i>
                                            </li>
                                            <li class="text-right text-success">
                                                {{$categoryinfographic_count}}
                                            </li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-6">
                            <div class="card client-blocks success-border">
                                <div class="card-block">
                                    <a href="{{route('admin.infographics.index')}}">
                                        <h5>ระบบจัดการกิจกรรม</h5>
                                        <ul>
                                            <li>
                                                <i class="icofont icofont-social-photobucket text-success"></i>
                                            </li>

                                            <li class="text-right text-success">
                                                {{$infographic_count}}
                                            </li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-6">
                            <div class="card client-blocks warning-border">
                                <div class="card-block">
                                    <a href="{{route('admin.category.index')}}">
                                        <h5>ระบบจัดการหมวดหมู่วีดีโอ</h5>
                                        <ul>
                                            <li>
                                                <i class="icofont icofont-brand-youtube text-warning"></i>
                                            </li>
                                            <li class="text-right text-warning">
                                                {{$category_count}}
                                            </li>
                                        </ul>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-6">
                            <div class="card client-blocks warning-border">
                                <div class="card-block">
                                    <a href="{{route('admin.youtube.index')}}">
                                        <h5>ระบบจัดการวีดีโอ</h5>
                                        <ul>
                                            <li>
                                                <i class="icofont icofont-brand-youtube text-warning"></i>
                                            </li>
                                            <li class="text-right text-warning">
                                                {{$youtube_count}}
                                            </li>
                                        </ul> 
                                    </a>
                                </div>
                            </div>
                        </div>
                        <!-- New files card end -->
                        <!-- Open Project card start -->
                    </div>
                </div>
                <!-- Round card end -->
            </div>
        </div>
        <!-- Main-body end -->
        <div id="styleSelector">
        </div>
    </div>
</div>
@endsection
 @section('jsfooter')
<script type="text/javascript" src="assets/js/animation.js"></script> 
@endsection