app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', 'ChannelController@index');
Route::get('/index', 'ChannelController@index');
Route::auth();

Route::get('/admin', 'HomeController@index')->name('adminindex');

Route::get('/Contact', 'ChannelController@Contact');
Route::get('/Livestream', 'ChannelController@Livestream');
Route::get('/History', 'ChannelController@History');
Route::get('/feeds' , 'ChannelController@NewsFeed');
Route::get('/nacc' , 'ChannelController@Nacc');
Route::get('/pacc' , 'ChannelController@Pacc');
Route::get('/test' , 'ChannelController@Test');

Route::resource('/admin/infographics','InfoGraphicController');
Route::resource('/admin/youtube','YoutubeController');
//Route::resource('/library','LibraryController');
Route::resource('/admin/newstopic','NewsController');
Route::resource('/admin/category','CategoryController');
Route::resource('/admin/categorynews','CategoryNewsController');
Route::resource('/admin/categoryinfographics','CategoryInfographicController');
//Route::resource('/playyoutube','PlayYoutubeController');
// manage user 
Route::resource('/admin/users','UsersController');

Route::delete('/ajaxdeletenewsdetail/{id}', 'NewsController@ajaxdeletenewsdetail')->name('ajaxdeletenewsdetail');
Route::post('/ajaxupdateview', 'ChannelController@ajaxupdateview')->name('ajaxupdateview'); 
Route::post('/ajaxupdateviewinfographic', 'ChannelController@ajaxupdateinfographic')->name('ajaxupdateinfographic'); 
Route::post('/ajaxupdateviewnews', 'ChannelController@ajaxupdateviewnews')->name('ajaxupdateviewnews');//Ajax Route to function ajaxupdateview
Route::get('PlayYoutube/{id}', [
    'as' => 'PlayYoutube',
    'uses' => 'ChannelController@PlayYoutube'
]);
Route::resource('playyoutube', 'ChannelController', ['except' => 'PlayYoutube']);

Route::get('Category/{id}', [
    'as' => 'Category',
    'uses' => 'ChannelController@Category'
]);
Route::resource('Category', 'ChannelController', ['except' => 'Category']);

Route::get('Infographic/{id}', [
    'as' => 'Infographic',
    'uses' => 'ChannelController@Infographic'
]);
Route::resource('viewinfographicc', 'ChannelController', ['except' => 'Infographic']);

Route::get('News/{id}', [
    'as' => 'News',
    'uses' => 'ChannelController@News'
]);
Route::resource('viewnews', 'ChannelController', ['except' => 'News']);

Route::get('Detailnews/{id}', [
    'as' => 'Detailnews',
    'uses' => 'ChannelController@Detailnews'
]);
Route::resource('viewdetailnew', 'ChannelController', ['except' => 'Detailnews']);

app/CategoryNewsTable.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CategoryNewsTable extends Model
{
    protected $table = 'CategoryNews';

    public function news(){
        return $this->hasMany(News::class,'CategoryNews_id');
    }
}

app/Http/Controllers/CategoryNewsController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\CategoryNewsTable;
use Image;
use File;
use Illuminate\Support\Facades\Auth; //เอาออเทนมาใช้

class CategoryNewsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorynews = CategoryNewsTable::where('is_public',1)->get(); 
        return view('categorynews.index',compact('categorynews'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categorynews.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required'
        ],[
            'name.required'=> 'กรุณากรอกชื่อประเภทข่าวประชาสัมพันธ์'
        ]);

         $categorynews = new CategoryNewsTable(); 
         $categorynews->name = $request->name;
         $categorynews->create_by = Auth::user()->name;
         $categorynews->is_public = 1;
         $categorynews->save();
         return redirect()->route('admin.categorynews.index')->with('feedback','บันทึกข้อมูลเรียบร้อยแล้ว');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $categorynews = CategoryNewsTable::findOrFail($id); 
      return view('categorynews.edit',compact('categorynews'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
            'name' => 'required',
        ],[
            'name.required'=> 'กรุณากรอกชื่อประเภทข่าวประชาสัมพันธ์',
        ]);
        $categorynews = CategoryNewsTable::find($id); 
        $categorynews->name = $request->name;
        $categorynews->save();
        return redirect()->route('admin.categorynews.index')->with('feedback','แก้ไขข้อมูลเรียบร้อยแล้ว');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categorynews = CategoryNewsTable::find($id);
        $categorynews->is_public = 0;
        $categorynews->save();

        if($categorynews){
            return response()->json(['success' => '1']);                    
        }else{
            return response()->json(['success' => '0']);                    
        }
    }
}

resources/views/categorynews/create.blade.php
@extends('layouts.master')

@section('content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
                <div class="page-wrapper">
                    <!-- Page-header start -->
                    <div class="page-header">
                        <div class="page-header-title">
                            <h4>เพิ่มหมวดหมู่ข่าวประชาสัมพันธ์</h4>
                            <span></span>
                        </div>
                        <div class="page-header-breadcrumb">
                            <ul class="breadcrumb-title">
                                <li class="breadcrumb-item">
                                    <a href="{{url('/')}}">
                                        <i class="icofont icofont-home"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item"><a href="{{route('admin.categorynews.index')}}">หมวดหมู่ข่าวประชาสัมพันธ์</a>
                                <li class="breadcrumb-item"><a href="#">เพิ่มหมวดหมู่ข่าวประชาสัมพันธ์</a>
                            </ul>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">
                            <h5>เพิ่มข้อมูล</h5>
                        </div>
                        <div class="card-block">
                            {!! Form::open(array('route' => 'admin.categorynews.store' , 'method' => 'post' , 'files' => true )) !!}
                                {{ csrf_field() }}

                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">ชื่อหมวดหมู่ข่าวประชาสัมพันธ์</label>
                                    <div class="col-sm-10">
                                        <?= Form::text('name',null,['class'=>'form-control','placeholder'=>'ชื่อประเภทข่าวประชาสัมพันธ์']);?>
                                        <span class="messages"></span>
                                        @if ($errors->has('name'))
                                        <span class="messages"><p class="text-danger error">{{ $errors->first('name')}}</p></span>
                                        @endif
                                    </div>
                                </div>

                                {{-- <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">รูปภาพปก</label>
                                    <div class="col-sm-10">
                                            <div class="col-lg-3 col-md-6 col-sm-12">
                                                <a onclick="$('#imgInp').click();">      
                                                <img id="blah" style="cursor:pointer;" src="{{asset('images/nopic.png')}}" alt="รูปภาพปก"  class="img-fluid" /></a>
                                            </div>
                                        <div style="margin-button:20px"></div><br>
                                        <input type="file" id="imgInp" name="image" style="display:none;cursor:pointer;" accept="image/jpg, image/jpeg, image/png" >   
                                        <span class="messages"></span>
                                        @if ($errors->has('image'))
                                        <span class="messages"><p class="text-danger error">{{ $errors->first('image')}}</p></span>
                                        @endif         
                                    </div>        
                                </div> --}}

                                <div class="form-group row">
                                    <label class="col-sm-2"></label>
                                    <div class="col-sm-10">
                                        <button data-key="submit" type="submit" class="btn btn-primary" > <i class="ion-archive"></i>บันทึก</button>
                                        <a href="{{ route('admin.categorynews.index') }}" class="btn btn-default">
                                            <i class="ion-reply"></i>ยกเลิก
                                        </a>
                                    </div>
                                </div>
                            {!! Form::close() !!}    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('jsfooter')
<script>
      $(document).ready(function() {
            document.getElementById('main_news').classList.add('active');
            document.getElementById('main_news').classList.add('pcoded-trigger');
            document.getElementById('categorynews_active').classList.add('active');
    });
    //image headline Show
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $('#blah').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
        $("#imgInp").change(function() {readURL(this);});
</script>
@endsection

resources/views/categorynews/edit.blade.php
@extends('layouts.master')


@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>แก้ไขข่าวประชาสัมพันธ์</h4>
                        <span></span>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="{{url('/admin')}}">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="{{route('admin.categorynews.index')}}">หมวดหมู่ข่าวประชาสัมพันธ์</a>
                            <li class="breadcrumb-item"><a href="#">แก้ไข</a>  
                        </ul>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <h5>แก้ไข </h5>
                    </div>
                    <div class="card-block">
                    {!! Form::model($categorynews,['route' => ['admin.categorynews.update',$categorynews->id],'method'=> 'put','files'=>true,'name'=>'form','id'=>'formCreate'])
                    !!} {{ csrf_field() }}
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">หมวดหมู่ข่าวประชาสัมพันธ์</label>
                                <div class="col-sm-10">
                                <?= Form::text('name',null,['class'=>'form-control','placeholder'=>'หมวดหมู่ข่าวประชาสัมพันธ์']);?>
                                <span class="messages"></span>
                                    @if ($errors->has('name'))
                                <span class="messages"><p class="text-danger error">{{ $errors->first('name')}}</p></span>
                                    @endif
                            </div>
                        </div>
                            
                        {{-- <div class="form-group row">
                            <label class="col-sm-2 col-form-label">รูปภาพปก</label>
                                <div class="col-sm-10">
                                    <div class="col-lg-3 col-md-6 col-sm-12">
                                        <a onclick="$('#imgInp').click();">  
                                        <img id="blah" style="cursor:pointer;" src="{{asset('categoryimages/') .'/'. $category->image }}" class="img-fluid"  alt="รูปภาพปก"></a><br>
                                    </div>
                                </div>
                            <div style="margin-button:20px"></div><br>
                            <input type="file" style="display:none;cursor:pointer;" id="imgInp" name="image" accept="image/jpg, image/jpeg, image/png" >
                        </div> --}}

                        <div class="form-group row">
                            <label class="col-sm-2"></label>
                            <div class="col-sm-10">
                                <button data-key="submit" type="submit" class="btn btn-primary" > <i class="ion-archive"></i>บันทึก</button>
                                <a href="{{ route('admin.categorynews.index') }}" class="btn btn-default">
                                <i class="ion-reply"></i>ยกเลิก</a>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('jsfooter')
<script>
      $(document).ready(function() {
            document.getElementById('main_news').classList.add('active');
            document.getElementById('main_news').classList.add('pcoded-trigger');
            document.getElementById('categorynews_active').classList.add('active');
    });
    //image headline Show
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $('#blah').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
        $("#imgInp").change(function() {readURL(this);});

</script>
@endsection

resources/views/categorynews/index.blade.php
@extends('layouts.master')
@section('content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">    
        <div class="main-body">
            <div class="page-wrapper">
                    @if(session('feedback'))
                        <div class="alert alert-success alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Success!</strong> {{ session('feedback') }}
                        </div>
                    @endif
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>หมวดหมู่ข่าวประชาสัมพันธ์</h4>
                        <span></span>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="{{url('/admin')}}">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="">หมวดหมู่ข่าวประชาสัมพันธ์</a>
                        </ul>
                    </div>
                </div>
                <!-- Hover table card start -->
                <div class="card">
                    <div class="card-header">
                            <a href="{{route('admin.categorynews.create')}}">
                        <h5><button class="btn btn-info btn-md"><i class="ion-plus"></i>เพิ่มข้อมูล</button></h5>
                        <span></span></a>
                        <div class="card-header-right">
                            
                        </div>
                    </div>
                    <div class="card-block">
                        <div class="dt-responsive table-responsive">
                            <table id="simpletable" class="table table-striped table-bordered nowrap">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th width="75%">ชื่อ</th> 
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $i = 1; @endphp
                                    @foreach($categorynews as $row)
                                    <tr>
                                        <td>{{$i}}</td>
                                        <td>{{$row->name}}</td>
                                        <td> 
                                            <a href="{{ route('admin.categorynews.edit',$row->id) }}" class="btn   btn-warning waves-effect waves-light"><i class="fa fa-pencil"></i> แก้ไข</a>
                                            <a href="" class=" btn btn-danger  waves-effect waves-light delBtn" data-id="{{$row->id}}" data-refrow="{{$row->news->count()}}"><i class="fa fa-times" ></i> ลบ</a>
                                            <input type="hidden" name="_token" id="_token" value="{{ csrf_token() }}">
                                        </td>
                                    </tr>
                                    @php $i++; @endphp
                                    @endforeach
                                </tbody>  
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('jsfooter')
<script>
    $(document).ready(function() {
            document.getElementById('main_news').classList.add('active');
            document.getElementById('main_news').classList.add('pcoded-trigger');
            document.getElementById('categorynews_active').classList.add('active');
    });
		window.setTimeout(function(){
            $('.alert').fadeTo(500,0).slideUp(500,function(){
                $(this).remove();
            })
        }, 3000);

        $(document).on('click', '.delBtn', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var refrow = $(this).data('refrow');
            swal({
                title: "คุณต้องการลบ?",
                text: "มีข้อมูลข่าวประชาสัมพันธ์ที่เกี่ยวข้องกับประเภทนี้อยู่ " + refrow + " รายการ หากคุณทำการลบข้อมูล จะไม่สามารถทำการกู้คืนได้อีก",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        method: "DELETE",
                        url: '{{ url('admin/categorynews')}}/'+id,
                        data: {ids:id,_token: $('#_token').val(),},
                        success: function (data) {
                            if(data.success =="1"){
                                swal("ทำการลบข้อมูลสำเร็จ", {
                                    icon: "success",
                                }).then(()=>{ location.reload(); });     
                            }else{
                                swal({
                                    title:"พบข้อผิดพลาด",
                                    text: "กรุณาติดต่อผู้ดูแลระบบ",
                                    icon: "warning",
                                    dangerMode: true,
                                });
                            }
                        }         
                    });
                } else {
                    //swal("ยกเลิกการลบข้อมูล");
                }
            });
        });
    </script>
@endsection