app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', 'ChannelController@index');
Route::get('/index', 'ChannelController@index');
Route::auth();

Route::get('/admin', 'HomeController@index')->name('adminindex');

Route::get('/Contact', 'ChannelController@Contact');
Route::get('/Livestream', 'ChannelController@Livestream');
Route::get('/History', 'ChannelController@History');
Route::get('/feeds' , 'ChannelController@NewsFeed');
Route::get('/nacc' , 'ChannelController@Nacc');
Route::get('/pacc' , 'ChannelController@Pacc');
Route::get('/test' , 'ChannelController@Test');

Route::resource('/admin/infographics','InfoGraphicController');
Route::resource('/admin/youtube','YoutubeController');
//Route::resource('/library','LibraryController');
Route::resource('/admin/newstopic','NewsController');
Route::resource('/admin/category','CategoryController');
Route::resource('/admin/categorynews','CategoryNewsController');
Route::resource('/admin/categoryinfographics','CategoryInfographicController');
//Route::resource('/playyoutube','PlayYoutubeController');
// manage user 
Route::resource('/admin/users','UsersController');

Route::delete('/ajaxdeletenewsdetail/{id}', 'NewsController@ajaxdeletenewsdetail')->name('ajaxdeletenewsdetail');
Route::post('/ajaxupdateview', 'ChannelController@ajaxupdateview')->name('ajaxupdateview'); 
Route::post('/ajaxupdateviewinfographic', 'ChannelController@ajaxupdateinfographic')->name('ajaxupdateinfographic'); 
Route::post('/ajaxupdateviewnews', 'ChannelController@ajaxupdateviewnews')->name('ajaxupdateviewnews');//Ajax Route to function ajaxupdateview
Route::get('PlayYoutube/{id}', [
    'as' => 'PlayYoutube',
    'uses' => 'ChannelController@PlayYoutube'
]);
Route::resource('playyoutube', 'ChannelController', ['except' => 'PlayYoutube']);

Route::get('Category/{id}', [
    'as' => 'Category',
    'uses' => 'ChannelController@Category'
]);
Route::resource('Category', 'ChannelController', ['except' => 'Category']);

Route::get('Infographic/{id}', [
    'as' => 'Infographic',
    'uses' => 'ChannelController@Infographic'
]);
Route::resource('viewinfographicc', 'ChannelController', ['except' => 'Infographic']);

Route::get('News/{id}', [
    'as' => 'News',
    'uses' => 'ChannelController@News'
]);
Route::resource('viewnews', 'ChannelController', ['except' => 'News']);

Route::get('Detailnews/{id}', [
    'as' => 'Detailnews',
    'uses' => 'ChannelController@Detailnews'
]);
Route::resource('viewdetailnew', 'ChannelController', ['except' => 'Detailnews']);

app/Http/Controllers/YoutubeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Video;
use App\CategoryTable;
use Image;
use File;
use Illuminate\Support\Facades\Auth; //เอาออเทนมาใช้

class YoutubeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $youtube = Video::with('category')->where('is_public',1)->get(); 
        return view('youtube.index',compact('youtube'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('youtube.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'Category_id' => 'required',
            'title' => 'required',
            'link' => 'required',
            'description' => 'required'
        ],[
            'Category_id.required' => 'กรุณาเลือกประเภท',
            'title.required'=> 'กรุณากรอกชื่อ',
            'link.required' => 'กรุณากรอก Link',
            'description.required'=> 'กรุณากรอกรายละเอียด',
        ]);
        $youtube = new Video(); 
        $youtube->Category_id = $request->Category_id;
        $youtube->title = $request->title;
        $youtube->link = $request->link;
        $youtube->description = $request->description;
        $youtube->view = 0;
        $youtube->is_public = 1;
        $youtube->create_by = Auth::user()->name;
        $youtube->startdate = $request->startdate;
        $youtube->enddate = $request->enddate;
        $youtube->save();
        return redirect()->route('admin.youtube.index')->with('feedback','บันทึกข้อมูลเรียบร้อยแล้ว');
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $youtube_obj = Video::findOrFail($id); 
        return view('youtube.edit',compact('youtube_obj'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'Category_id' => 'required',
            'title' => 'required',
            'link' => 'required',
            'description' => 'required',
            'startdate' => 'required',
            
        ],[
            'Category_id.required' => 'กรุณาเลือกประเภท',
            'title.required'=> 'กรุณากรอกชื่อ',
            'link.required' => 'กรุณากรอก Link',
            'description.required'=> 'กรุณากรอกรายละเอียด',
            'startdate.required' => 'กรุณาใส่วันเริ่ม',
            
           
        ]);
        $youtube = Video::find($id);
        $youtube->Category_id = $request->Category_id;
        $youtube->title = $request->title;
        $youtube->link = $request->link;
        $youtube->description = $request->description;
        $youtube->startdate = $request->startdate;
        $youtube->enddate = $request->enddate;
         
         $youtube->save();
         return redirect()->route('admin.youtube.index')->with('feedback','แก้ไขข้อมูลเรียบร้อยแล้ว');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $youtube = Video::find($id);
        $youtube->is_public = 0;
        $youtube->save();

        if($youtube){
            return response()->json(['success' => '1']);                    
        }else{
            return response()->json(['success' => '0']);                    
        }
    }
}

resources/views/youtube/create.blade.php
@extends('layouts.master') 
@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>เพิ่มวีดีโอ</h4>
                        <span></span>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="{{url('/')}}">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{route('admin.youtube.index')}}">วีดีโอ</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">เพิ่มวีดีโอ</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <h5>เพิ่มข้อมูล</h5>
                        <span></span>
                    </div>
                    <div class="card-block">
                        {!! Form::open(array('route' => 'admin.youtube.store' , 'method' => 'post' )) !!} {{ csrf_field() }}
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">หมวดหมู่วีดีโอ</label>
                            <div class="col-sm-10">
                                {!! Form::select('Category_id', App\CategoryTable::where('is_public' , 1)->orderby('name','asc')->pluck('name','id'), null,
                                ['placeholder' => 'กรุณาเลือกหมวดหมู่','class' => 'form-control']); !!} @if ($errors->has('Category_id'))
                                <span class="messages">
                                    <p class="text-danger error">{{ $errors->first('Category_id')}}</p>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">ชื่อวีดีโอ</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="title" id="title" placeholder="กรุณากรอกชื่อวีดีโอ"> @if ($errors->has('title'))
                                <span class="messages">
                                    <p class="text-danger error">{{ $errors->first('title')}}</p>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="exampleTextarea" class="col-2 col-form-label">Link</label>
                            <div class="col-10">
                                {{--
                                <textarea class="form-control" id="link" name="link" rows="3" placeholder="กรุณากรอก Link"></textarea> --}}
                                <?= Form::text('link',null,['class'=>'form-control','placeholder'=>'กรุณาใส่ Link']);?>
                                    @if ($errors->has('link'))
                                    <span class="messages">
                                        <p class="text-danger error">{{ $errors->first('link')}}</p>
                                    </span>
                                    @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">รายละเอียด</label>
                            <div class="col-sm-10">
                                {!! Form::textarea('description',null,['class'=>'form-control','placeholder'=>'กรุณากรอกรายละเอียด']); !!} @if ($errors->has('description'))
                                <span class="messages">
                                    <p class="text-danger error">{{ $errors->first('description')}}</p>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="exampleTextarea" class="col-sm-2 col-form-label">วันที่เริ่ม</label>
                            <div class="col-10">
                                    {!! Form::date('startdate',null,['class'=>'form-control']);!!}
                                @if ($errors->has('startdate'))
                                <span class="messages"><p class="text-danger error">{{ $errors->first('startdate')}}</p></span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="exampleTextarea" class="col-sm-2 col-form-label">วันที่สิ้นสุด</label>
                            <div class="col-10">
                                    {!! Form::date('enddate',null,['class'=>'form-control']);!!}
                                @if ($errors->has('enddate'))
                                <span class="messages"><p class="text-danger error">{{ $errors->first('enddate')}}</p></span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2"></label>
                            <div class="col-sm-10">
                                <button data-key="submit" type="submit" class="btn btn-primary">
                                    <i class="ion-archive"></i>บันทึก</button>
                                <a href="{{ route('admin.youtube.index') }}" class="btn btn-default">
                                    <i class="ion-reply"></i>ยกเลิก
                                </a>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('jsfooter')
<script>
        $(document).ready(function() {
             document.getElementById('main_youtube').classList.add('active');
             document.getElementById('main_youtube').classList.add('pcoded-trigger');
             document.getElementById('youtube_active').classList.add('active');
     });
</script>
@endsection

resources/views/youtube/edit.blade.php
@extends('layouts.master') 
@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>แก้ไขวีดีโอ</h4>
                        <span></span>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="{{url('/')}}">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{route('admin.youtube.index')}}">วีดีโอ</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="">แก้ไขวีดีโอ</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h5>แก้ไข</h5>
                        <div class="card-header-right">
                        </div>
                    </div>
                    <div class="card-block">
                        {!! Form::model($youtube_obj,['route' => ['admin.youtube.update',$youtube_obj->id],'method'=> 'put', 'name'=>'form','id'=>'formCreate'])!!}
                        {{ csrf_field() }}
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">หมวดหมู่</label>
                            <div class="col-sm-10">
                                {!! Form::select('Category_id', App\CategoryTable::orderby('name','asc')->pluck('name','id'), null, ['placeholder' => 'กรุณาเลือกหมวดหมู่','class'
                                => 'form-control']); !!} @if ($errors->has('Category_id'))
                                <span class="messages">
                                    <p class="text-danger error">{{ $errors->first('Category_id')}}</p>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">ชื่อวีดีโอ</label>
                            <div class="col-sm-10">
                                <?= Form::text('title',null,['class'=>'form-control','placeholder'=>'กรุณากรอกชื่อวีดีโอ']);?>
                                    <span class="messages"></span>
                                    @if ($errors->has('title'))
                                    <span class="messages">
                                        <p class="text-danger error">{{ $errors->first('title')}}</p>
                                    </span>
                                    @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Link</label>
                            <div class="col-sm-10">
                                <?= Form::text('link',null,['class'=>'form-control','placeholder'=>'กรุณาใส่ลิ้ง']);?>
                                    <span class="messages"></span>
                                    @if ($errors->has('link'))
                                    <span class="messages">
                                        <p class="text-danger error">{{ $errors->first('link')}}</p>
                                    </span>
                                    @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">รายละเอียด</label>
                            <div class="col-sm-10">
                                {!! Form::textarea('description',null,['class'=>'form-control','placeholder'=>'กรุณากรอกรายละเอียด']); !!} 
                                @if ($errors->has('description'))
                                <span class="messages">
                                    <p class="text-danger error">{{ $errors->first('description')}}</p>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="exampleTextarea" class="col-sm-2 col-form-label">วันที่เริ่ม</label>
                            <div class="col-10">
                                {!! Form::date('startdate',null,['class'=>'form-control']);!!} 
                                @if ($errors->has('startdate'))
                                <span class="messages">
                                    <p class="text-danger error">{{ $errors->first('startdate')}}</p>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="exampleTextarea" class="col-sm-2 col-form-label">วันที่สิ้นสุด</label>
                            <div class="col-10">
                                {!! Form::date('enddate',null,['class'=>'form-control']);!!} 
                                @if ($errors->has('enddate'))
                                <span class="messages">
                                    <p class="text-danger error">{{ $errors->first('enddate')}}</p>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2"></label>
                            <div class="col-sm-10">
                                <button data-key="submit" type="submit" class="btn btn-primary">
                                    <i class="ion-archive"></i>บันทึก</button>
                                <a href="{{ route('admin.youtube.index') }}" class="btn btn-default">
                                    <i class="ion-reply"></i>ยกเลิก</a>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@endsection
@section('jsfooter')
<script>
        $(document).ready(function() {
             document.getElementById('main_youtube').classList.add('active');
             document.getElementById('main_youtube').classList.add('pcoded-trigger');
             document.getElementById('youtube_active').classList.add('active');
     });
</script>
@endsection

resources/views/youtube/index.blade.php
@extends('layouts.master')
@section('content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">   
        <div class="main-body">
            <div class="page-wrapper">
                @if(session('feedback'))
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Success!</strong> {{ session('feedback') }}
                    </div>
                @endif
                @if(session('feedbackdelete'))
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Success!</strong> {{ session('feedbackdelete') }}
                    </div>
                @endif
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="page-header-title">
                        <h4>วีดีโอ</h4>
                        <span></span>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="{{url('/')}}">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="">วีดีโอ</a>
                            
                        </ul>
                    </div>
                </div>
                <!-- Hover table card start -->
                <div class="card">
                    <div class="card-header">
                            <a href="{{route('admin.youtube.create')}}">
                        <h5><button class="btn btn-info"><i class="ion-plus"></i>เพิ่มข้อมูล</button></h5>
                        <span></span></a>
                        <div class="card-header-right">
                        </div>
                    </div>
                    <div class="card-block">
                        <div class="dt-responsive table-responsive">
                            <table id="simpletable" class="table table-striped table-bordered nowrap">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>หมวดหมู่</th>
                                        <th>ชื่อวีดีโอ</th>
                                        <th>Link</th>
                                        <th>รายละเอียด</th>
                                        <th>view</th>
                                        <th>create_by</th>
                                        <th>วันที่เริ่ม</th>
                                        <th>วันที่สิ้นสุด</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($youtube as $i=>$row)
                                    <tr>
                                        <td>{{$i+1}}</td>
                                        <td>{{$row->category->name}}</td>
                                        <td>{{$row->title}}</td>
                                        <td>{{$row->link}}</td>
                                        <td> 
                                            <button type="button" class="btn btn-inverse waves-effect " data-toggle="modal" data-target="#description{{$row->id}}"><i class="ion-ios-search"></i></button>
                                        </td>
                                        <td>{{$row->view}}</td>
                                        <td>{{$row->create_by}}</td>
                                        <td>{{DateTime::createFromFormat('Y-m-d', $row->startdate)->format('d-m-Y') }}</td>
                                        <td>{{DateTime::createFromFormat('Y-m-d', $row->enddate)->format('d-m-Y') }}</td>
                                        <td>
                                            <a href="{{ route('admin.youtube.edit',$row->id) }}" class="btn   btn-warning waves-effect waves-light"><i class="fa fa-pencil"></i> แก้ไข</a>
                                            <a href="" class=" btn btn-danger  waves-effect waves-light delBtn" data-id="{{$row->id}}"><i class="fa fa-times" ></i> ลบ</a>
                                            <input type="hidden" name="_token" id="_token" value="{{ csrf_token() }}">
                                        </td>
                                    </tr>      
                                    <!-- Modal description-->
                                    <div class="modal fade" id="description{{$row->id}}" tabindex="-1" role="dialog">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">{{$row->title}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true" style="font-size: 1.50em;cursor: pointer;"><i class="ion-close-circled"></i></span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                @php echo $row->description @endphp
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Modal description-->
                                    @php $i++ @endphp
                                    @endforeach
                                </tbody>  
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </div>
</div>

@endsection
@section('jsfooter')
<script>
       $(document).ready(function() {
            document.getElementById('main_youtube').classList.add('active');
            document.getElementById('main_youtube').classList.add('pcoded-trigger');
            document.getElementById('youtube_active').classList.add('active');
    });
		window.setTimeout(function(){
            $('.alert').fadeTo(500,0).slideUp(500,function(){
                $(this).remove();
            })
        }, 3000);

$(document).on('click', '.delBtn', function (e) {
            
            e.preventDefault();
            var id = $(this).data('id');
            // alert(id);
            swal({
                title: "คุณต้องการลบ?",
                text: "หากคุณทำการลบข้อมูล จะไม่สามารถทำการกู้คืนได้อีก",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    // alert(id);
                    $.ajax({
                            method: "DELETE",
                            url: '{{ url('admin/youtube')}}/'+id,
                            data: {ids:id,_token: $('#_token').val(),},
                            success: function (data) {
                                if(data.success =="1"){
                                    swal("ทำการลบข้อมูลสำเร็จ", {
                                        icon: "success",
                                    }).then(()=>{ location.reload(); });     
                                }else{
                                    swal({
                                        title:    "พบข้อผิดพลาด",
                                        text: "กรุณาติดต่อผู้ดูแลระบบ",
                                        icon: "warning",
                                        dangerMode: true,
        
                                    });
                                }
                            }         
                    });
                } else {
                    //swal("ยกเลิกการลบข้อมูล");
                }
            });
        });
    </script>
@endsection